export const themes = {
    natural: {
        background: "#9e9992",
        background2: "#5f5a54",
        band: "#232220",
        image: "url('/assets/backgrounds/wallpaper1.webp')",
    },
    blue: {
        background: "#3a4252",
        background2: "#1e232e",
        band: "#1c1c1f",
        image: "url('/assets/backgrounds/wallpaper2.jpeg')",
    },
    white: {
        background: "#b6b3af",
        background2: "#2e2d2a",
        band: "#575753",
        image: "url('/assets/backgrounds/wallpaper3.webp')",
    },
    black: {
        background: "#393a3d",
        background2: "#1d1d1f",
        band: "#1e1e1e",
        image: "url('/assets/backgrounds/wallpaper4.webp')",
    },
};

export const defaultIsleApps = ["messages", "mail", "safari", "phone"];

export const defaultApps = [
    [
        "facetime",
        "calendar",
        "photos",
        "camera",
        "music",
        "notes",
        "reminders",
        "clock",
        "news",
        "tv",
        "podcasts",
        "app-store",
        "maps",
        "health",
        "wallet",
        "settings",
    ],
    [
        "wallet",
        "photos",
        "fitness",
        "music",
        "shortcuts",
        "find-my",
        "app-store",
        "measure",
        "pages",
        "safari",
        "health",
    ],
    [
        "contacts",
        "clock",
        "magnifier",
        "phone",
        "notes",
        "maps",
        "calendar",
        "numbers",
        "translate",
        "keynote",
        "homekit",
    ],
    [
        "settings",
        "freeform",
        "tips",
        "garageband",
        "health",
        "news",
        "siri",
        "stocks",
        "files",
        "mail",
        "clips",
        "itunes-store",
        "weather",
        "compass",
    ],
    [
        "voicememo",
        "imovie",
        "messages",
        "watch",
        "reminders",
        "camera",
        "tv",
        "podcasts",
        "books",
        "calculator",
        "apple-store",
        "facetime",
    ],
];
